name: var_widget
description: A new state manangment for flutter
version: 0.1.0
author: 강동윤 <kdy1@outlook.kr>
homepage: 'https://github.com/kdy1/var_widget'

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec